#!/usr/bin/env bash
# Parses Apache log files in list format.
#   Groups visitors by IP and HTTP status code.
#   Displays the number of occurrences, IP, and HTTP status

awk '{count[$1 " " $9]++} END {for (ip_code in count) print count[ip_code], ip_code}' apache-access.log | sort -nr
