#!/usr/bin/env bash
# Displays the contents of the current directory in list format.
#   Only displays the part of the name after the first dash. 

for file in *
do
  if [ -f "$file" ] && [[ "$file" != .* ]] && [[ "$file" == *-* ]]
  then
    echo "${file#*-}"
  fi
done
